blank_issues_enabled: false
contact_links:
  - name: Want to Discuss something?
    url: https://github.com/DSC-SIST/Event-Aggregator/discussions/
    about: For any Discussion, Query.
  - name: Guidelines
    url: https://github.com/DSC-SIST/Event-Aggregator/blob/master/CONTRIBUTING.md
    about: Our contribution guidelines (Please go through them).
